/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    cursos: Curso;
    'galeria-imagenes': GaleriaImagene;
    galerias: Galeria;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cursos: CursosSelect<false> | CursosSelect<true>;
    'galeria-imagenes': GaleriaImagenesSelect<false> | GaleriaImagenesSelect<true>;
    galerias: GaleriasSelect<false> | GaleriasSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'configuracion-sitio': ConfiguracionSitio;
    'pagina-inicio': PaginaInicio;
    'pagina-bio': PaginaBio;
    'pagina-galeria': PaginaGaleria;
    'pagina-comercial': PaginaComercial;
    'pagina-novia': PaginaNovia;
    'pagina-contacto': PaginaContacto;
  };
  globalsSelect: {
    'configuracion-sitio': ConfiguracionSitioSelect<false> | ConfiguracionSitioSelect<true>;
    'pagina-inicio': PaginaInicioSelect<false> | PaginaInicioSelect<true>;
    'pagina-bio': PaginaBioSelect<false> | PaginaBioSelect<true>;
    'pagina-galeria': PaginaGaleriaSelect<false> | PaginaGaleriaSelect<true>;
    'pagina-comercial': PaginaComercialSelect<false> | PaginaComercialSelect<true>;
    'pagina-novia': PaginaNoviaSelect<false> | PaginaNoviaSelect<true>;
    'pagina-contacto': PaginaContactoSelect<false> | PaginaContactoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cursos".
 */
export interface Curso {
  id: number;
  /**
   * URL del curso, ej: peinado-inicial
   */
  slug: string;
  pageTitle: string;
  heroTitle: string;
  heroSubtitle?: string | null;
  intro?: {
    tag?: string | null;
    headingLines?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    lead?: string | null;
    paragraphs?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    chips?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    mainImage?: (number | null) | Media;
    mainImageAlt?: string | null;
    mainImageLabel?: string | null;
    secondaryImage?: (number | null) | Media;
    secondaryImageAlt?: string | null;
    secondaryImageLabel?: string | null;
  };
  learning?: {
    sectionTitle?: string | null;
    sectionLabel?: string | null;
    items?:
      | {
          num?: string | null;
          title: string;
          body: string;
          tag?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  director?: {
    photo?: (number | null) | Media;
    photoLabel?: string | null;
    photoYears?: string | null;
    sectionLabel?: string | null;
    nameLines?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    quote?: string | null;
    body?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  academy?: {
    sectionTitle?: string | null;
    sectionLabel?: string | null;
    name?: string | null;
    address?: string | null;
    addressStrong?: string | null;
    mapUrl?: string | null;
    modalities?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    photos?:
      | {
          photo?: (number | null) | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    sectionLabel?: string | null;
    headingLines?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    body?: string | null;
    instagramUrl?: string | null;
    email?: string | null;
    emailSubject?: string | null;
    includesLabel?: string | null;
    includes?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galeria-imagenes".
 */
export interface GaleriaImagene {
  id: number;
  imagen: number | Media;
  alt?: string | null;
  seccion: 'COMERCIAL' | 'EDITORIAL' | 'NOVIAS';
  grupo: string;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cada documento representa una sección de galería. Las imágenes se ordenan arrastrando las filas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galerias".
 */
export interface Galeria {
  id: number;
  /**
   * Segmento de URL: editorial · comercial · novias
   */
  slug: string;
  titulo: string;
  subtitulo?: string | null;
  seoTitle?: string | null;
  /**
   * Arrastra las filas para cambiar el orden. El orden aquí es el orden en el sitio.
   */
  imagenes?:
    | {
        imagen: number | Media;
        /**
         * Nombre del proyecto o cliente. Aparece como pie en el lightbox.
         */
        grupo?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'cursos';
        value: number | Curso;
      } | null)
    | ({
        relationTo: 'galeria-imagenes';
        value: number | GaleriaImagene;
      } | null)
    | ({
        relationTo: 'galerias';
        value: number | Galeria;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cursos_select".
 */
export interface CursosSelect<T extends boolean = true> {
  slug?: T;
  pageTitle?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  intro?:
    | T
    | {
        tag?: T;
        headingLines?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        lead?: T;
        paragraphs?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        chips?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        mainImage?: T;
        mainImageAlt?: T;
        mainImageLabel?: T;
        secondaryImage?: T;
        secondaryImageAlt?: T;
        secondaryImageLabel?: T;
      };
  learning?:
    | T
    | {
        sectionTitle?: T;
        sectionLabel?: T;
        items?:
          | T
          | {
              num?: T;
              title?: T;
              body?: T;
              tag?: T;
              id?: T;
            };
      };
  director?:
    | T
    | {
        photo?: T;
        photoLabel?: T;
        photoYears?: T;
        sectionLabel?: T;
        nameLines?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        quote?: T;
        body?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  academy?:
    | T
    | {
        sectionTitle?: T;
        sectionLabel?: T;
        name?: T;
        address?: T;
        addressStrong?: T;
        mapUrl?: T;
        modalities?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        photos?:
          | T
          | {
              photo?: T;
              alt?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        sectionLabel?: T;
        headingLines?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        body?: T;
        instagramUrl?: T;
        email?: T;
        emailSubject?: T;
        includesLabel?: T;
        includes?:
          | T
          | {
              texto?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galeria-imagenes_select".
 */
export interface GaleriaImagenesSelect<T extends boolean = true> {
  imagen?: T;
  alt?: T;
  seccion?: T;
  grupo?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galerias_select".
 */
export interface GaleriasSelect<T extends boolean = true> {
  slug?: T;
  titulo?: T;
  subtitulo?: T;
  seoTitle?: T;
  imagenes?:
    | T
    | {
        imagen?: T;
        grupo?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion-sitio".
 */
export interface ConfiguracionSitio {
  id: number;
  identidad?: {
    nombreSitio?: string | null;
    descripcionCorta?: string | null;
    email?: string | null;
    ubicacion?: string | null;
  };
  redes?: {
    instagram?: string | null;
    tiktok?: string | null;
    youtube?: string | null;
    pinterest?: string | null;
  };
  /**
   * Logos que aparecen en la sección de clientes.
   */
  marcas?:
    | {
        nombre: string;
        logo?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Logos de revistas que aparecen en la sección de prensa.
   */
  revistas?:
    | {
        nombre: string;
        logo?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        titulo: string;
        categoria?: ('COMERCIAL' | 'EDITORIAL') | null;
        cliente?: string | null;
        archivo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  footer?: {
    copyright?: string | null;
    tagline?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicio".
 */
export interface PaginaInicio {
  id: number;
  hero?: {
    subtitulo?: string | null;
  };
  bento?: {
    etiquetaGaleria?: string | null;
    etiquetaComerical?: string | null;
    etiquetaNovias?: string | null;
  };
  seo?: {
    titulo?: string | null;
    descripcion?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-bio".
 */
export interface PaginaBio {
  id: number;
  hero?: {
    titulo?: string | null;
    subtitulo?: string | null;
  };
  foto?: (number | null) | Media;
  /**
   * El primer párrafo aparece en tamaño mayor y cursiva.
   */
  parrafos?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    titulo?: string | null;
    descripcion?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-galeria".
 */
export interface PaginaGaleria {
  id: number;
  hero?: {
    titulo?: string | null;
    subtitulo?: string | null;
  };
  secciones?: {
    editorial?: string | null;
    comercial?: string | null;
    novias?: string | null;
  };
  seo?: {
    titulo?: string | null;
    descripcion?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-comercial".
 */
export interface PaginaComercial {
  id: number;
  hero?: {
    titulo?: string | null;
    subtitulo?: string | null;
  };
  seo?: {
    titulo?: string | null;
    descripcion?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-novia".
 */
export interface PaginaNovia {
  id: number;
  hero?: {
    titulo?: string | null;
    subtitulo?: string | null;
  };
  seo?: {
    titulo?: string | null;
    descripcion?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-contacto".
 */
export interface PaginaContacto {
  id: number;
  hero?: {
    titulo?: string | null;
    subtitulo?: string | null;
  };
  formulario?: {
    titulo?: string | null;
    descripcion?: string | null;
    emailDestino?: string | null;
    mensajeExito?: string | null;
  };
  seo?: {
    titulo?: string | null;
    descripcion?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion-sitio_select".
 */
export interface ConfiguracionSitioSelect<T extends boolean = true> {
  identidad?:
    | T
    | {
        nombreSitio?: T;
        descripcionCorta?: T;
        email?: T;
        ubicacion?: T;
      };
  redes?:
    | T
    | {
        instagram?: T;
        tiktok?: T;
        youtube?: T;
        pinterest?: T;
      };
  marcas?:
    | T
    | {
        nombre?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  revistas?:
    | T
    | {
        nombre?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        titulo?: T;
        categoria?: T;
        cliente?: T;
        archivo?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        copyright?: T;
        tagline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicio_select".
 */
export interface PaginaInicioSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        subtitulo?: T;
      };
  bento?:
    | T
    | {
        etiquetaGaleria?: T;
        etiquetaComerical?: T;
        etiquetaNovias?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-bio_select".
 */
export interface PaginaBioSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  foto?: T;
  parrafos?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-galeria_select".
 */
export interface PaginaGaleriaSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  secciones?:
    | T
    | {
        editorial?: T;
        comercial?: T;
        novias?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-comercial_select".
 */
export interface PaginaComercialSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-novia_select".
 */
export interface PaginaNoviaSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-contacto_select".
 */
export interface PaginaContactoSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  formulario?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        emailDestino?: T;
        mensajeExito?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}